#ifndef __ADMIN__H_
#define __ADMIN__H_

#include"MOUSE.H"
#include<stdio.h>
#include<stdlib.h>
#include<graphics.h>
#include"GROCERY.H"
#include<conio.h>


#define MENU_X1 0
#define MENU_Y1 0
#define MENU_X2 120
#define MENU_Y2 480
#define INTERFACE_A_X1 121
#define INTERFACE_A_Y1 0
#define INTERFACE_A_X2 380
#define INTERFACE_A_Y2 480
#define INTERFACE_B_X1 381
#define INTERFACE_B_Y1 0
#define INTERFACE_B_X2 640
#define INTERFACE_B_Y2 480


void drawgraph_admin_main(void);

#endif